server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pravallika42/olx-config
          username: Pravallika42
          password: ***********
          clone-on-start: true
     
